package DPSS_CORBA;


/**
* DPSS_CORBA/GameServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DPSS-CORBA.idl
* Tuesday, June 23, 2020 8:00:45 o'clock PM EDT
*/

public interface GameServer extends GameServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GameServer
