package DPSS_CORBA;


/**
* DPSS_CORBA/GameServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DPSS-CORBA.idl
* Tuesday, June 23, 2020 8:00:45 o'clock PM EDT
*/

public interface GameServerOperations 
{
  String createPlayerAccount (String FirstName, String LastName, float Age, String Username, String Password, String IPAddress);
  String playerSignIn (String Username, String Password, String IPAddress);
  String playerSignOut (String Username, String IPAddress);
  String getPlayerStatus (String AdminUsername, String AdminPassword, String IPAddress, boolean checkOtherServers);
  String transferAccount (String Username, String Password, String OldIPAddress, String NewIPAddress);
  String suspendAccount (String AdminUsername, String AdminPassword, String AdminIP, String UsernameToSuspend);
} // interface GameServerOperations
